name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup dell'ambiente Node.js (utilizzando una versione compatibile con Astro)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Installazione delle dipendenze
      - name: Install dependencies
        run: npm install

      # Step 4: Build del sito con Astro
      - name: Build site with Astro
        run: npm run build

      # Step 5: Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
